language: node_js
node_js:
   - 'stable'
cache:
  directories:
  - node_modules
branches:
only:
  - main
before_script:
  - npm install
script:
  - npm run compodoc
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: ./docs
  on:
    branch: main