language: node_js
node_js:
   - '9'
dist: trusty
sudo: required
branches:
only:
  - main
before_script:
  - npm install -g @compodoc/compodoc
script:
  - compodoc -p tsconfig.doc.json -n 'Prokey Link'  -d ./docs
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: ./docs
  on:
    branch: master